project_id = ""

[api]
port = 54321
schemas = []
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 14

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 604800
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.twitter]
enabled = true
client_id = ""
secret = ""
