[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/docs/*"
  status = 303
  to = "https://docs.feedbackcentral.io/*"

[[redirects]]
  from = "/blog/*"
  status = 303
  to = "https://docs.feedbackcentral.io/blog/*"